image: abesiyo/s3
pipelines:
  branches:
    master:
      - step:
          script:
            - s3 --region "ca-central-1" rm s3://market-tph-cdn-service
            - s3 --region "ca-central-1" sync . s3://market-tph-cdn-service