image: abesiyo/s3
pipelines:
  branches:
    master:
      - step:
          script:
            - s3 --region "<region>" rm s3://market-tph-cdn-service
            - s3 --region "<region>" sync . s3://market-tph-cdn-service